# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-20 08:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190120_0838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='durationtime',
            new_name='duration_time',
        ),
    ]
