# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-20 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190120_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='duration_time',
            field=models.TimeField(blank=True, default=None, null=True, verbose_name='Conversation Time'),
        ),
    ]
