# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-24 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190120_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_url',
            field=models.URLField(default=None, max_length=500, null=True, verbose_name='URL-Answer'),
        ),
    ]
