# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-28 05:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_question_question_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_url',
            field=models.TextField(default=None, max_length=500, null=True, verbose_name='URL-Answer'),
        ),
    ]
